
import React, { useState, useEffect, useRef } from 'react';
import { useApp } from '../context/AppContext';
import { Asset } from '../types';
import { QrCode, Box, ClipboardCheck, AlertTriangle, ChevronLeft, Camera, Check, Search, X, Package } from 'lucide-react';
import jsQR from 'jsqr';

type ViewState = 'HOME' | 'SCANNER' | 'ASSETS' | 'VERIFIED' | 'COMPLAINT' | 'DETAIL';

export const StaffModule = () => {
  const { assets, logs, verifyAsset, currentUser, addComplaint } = useApp();
  const [view, setView] = useState<ViewState>('HOME');
  const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null);
  const [scanInput, setScanInput] = useState('');
  const [complaintText, setComplaintText] = useState('');
  
  // Scanner Refs
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [scanError, setScanError] = useState<string>('');

  // Handle successful scan (string data)
  const handleScanResult = (data: string) => {
    let assetId = data;
    // Attempt to parse JSON if the QR was generated by our system
    try {
        const parsed = JSON.parse(data);
        if (parsed.assetId) {
            assetId = parsed.assetId;
        }
    } catch (e) {
        // Not JSON, assume raw ID
    }

    const asset = assets.find(a => a.id === assetId.trim() || a.serialNumber === assetId.trim());
    if(asset) {
        setSelectedAsset(asset);
        setView('DETAIL');
        setScanInput('');
    } else {
        alert(`Asset not found: ${assetId}`);
    }
  };

  const handleManualSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (scanInput.trim()) {
      handleScanResult(scanInput);
    }
  };

  const handleVerify = () => {
      if(selectedAsset && currentUser) {
          verifyAsset(selectedAsset.id, currentUser.name);
          setView('HOME');
      }
  };
  
  const handleComplaintSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if(selectedAsset && currentUser) {
          addComplaint({
              id: `c-${Date.now()}`,
              assetId: selectedAsset.id,
              assetName: selectedAsset.name,
              reportedBy: currentUser.name,
              date: new Date().toISOString(),
              description: complaintText,
              status: 'Pending'
          });
          setComplaintText('');
          setView('HOME');
      }
  };

  // Camera Logic
  useEffect(() => {
    let stream: MediaStream | null = null;
    let animationFrameId: number;

    const tick = () => {
        if (videoRef.current && videoRef.current.readyState === videoRef.current.HAVE_ENOUGH_DATA) {
            const canvas = canvasRef.current;
            if (canvas) {
                canvas.height = videoRef.current.videoHeight;
                canvas.width = videoRef.current.videoWidth;
                const ctx = canvas.getContext('2d');
                if (ctx) {
                    ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
                    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
                    const code = jsQR(imageData.data, imageData.width, imageData.height, {
                        inversionAttempts: "dontInvert",
                    });
                    
                    if (code && code.data) {
                        handleScanResult(code.data);
                        return; // Stop loop
                    }
                }
            }
        }
        animationFrameId = requestAnimationFrame(tick);
    };

    const startCamera = async () => {
        if (view === 'SCANNER') {
            try {
                setScanError('');
                stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
                if (videoRef.current) {
                    videoRef.current.srcObject = stream;
                    videoRef.current.setAttribute("playsinline", "true");
                    await videoRef.current.play();
                    requestAnimationFrame(tick);
                }
            } catch (err) {
                console.error("Camera access error:", err);
                setScanError('Camera access denied or unavailable. Please use manual entry.');
            }
        }
    };

    if (view === 'SCANNER') {
        startCamera();
    }

    return () => {
        if (stream) {
            stream.getTracks().forEach(track => track.stop());
        }
        cancelAnimationFrame(animationFrameId);
    };
  }, [view]);

  // 1. Staff Home
  if (view === 'HOME') {
    return (
      <div className="p-6 space-y-8 animate-in fade-in duration-300">
        <div className="bg-gradient-to-br from-indigo-600 to-violet-700 rounded-3xl p-8 text-white shadow-xl shadow-indigo-200 dark:shadow-none">
            <h1 className="text-3xl font-light mb-1">Hello, <span className="font-semibold">{currentUser?.name.split(' ')[0]}</span></h1>
            <p className="text-indigo-100 font-light">What would you like to do today?</p>
        </div>

        <div className="grid grid-cols-2 gap-4">
            <DashboardTile 
                icon={<QrCode size={32} />} 
                title="Scan QR" 
                subtitle="Verify Asset"
                color="bg-white dark:bg-slate-800 text-indigo-600 dark:text-indigo-400 border-indigo-100 dark:border-indigo-900" 
                onClick={() => setView('SCANNER')} 
                isPrimary
                fullWidth
            />
            <DashboardTile 
                icon={<Box size={24} />} 
                title="Assets" 
                subtitle="Browse All"
                color="bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300" 
                onClick={() => setView('ASSETS')} 
            />
            <DashboardTile 
                icon={<ClipboardCheck size={24} />} 
                title="History" 
                subtitle="Verified Items"
                color="bg-white dark:bg-slate-800 text-emerald-600 dark:text-emerald-400" 
                onClick={() => setView('VERIFIED')} 
            />
            <DashboardTile 
                icon={<AlertTriangle size={24} />} 
                title="Report" 
                subtitle="Raise Issue"
                color="bg-white dark:bg-slate-800 text-amber-500" 
                onClick={() => { setSelectedAsset(null); setView('COMPLAINT'); }} 
                fullWidth
            />
        </div>
      </div>
    );
  }

  // 2. Scanner View
  if (view === 'SCANNER') {
      return (
          <div className="fixed inset-0 bg-black text-white z-50 flex flex-col">
              <div className="p-6 flex justify-between items-center bg-gradient-to-b from-black/50 to-transparent absolute top-0 w-full z-10">
                   <button onClick={() => setView('HOME')} className="bg-white/10 backdrop-blur-md p-3 rounded-full hover:bg-white/20 transition-colors"><X size={24} /></button>
                   <span className="font-medium tracking-wide">Scan Asset QR</span>
                   <div className="w-12"></div>
              </div>
              
              <div className="flex-1 relative flex items-center justify-center bg-slate-900 overflow-hidden">
                  {!scanError ? (
                      <>
                        <video 
                            ref={videoRef} 
                            className="absolute inset-0 w-full h-full object-cover opacity-80" 
                            muted
                        />
                        <canvas ref={canvasRef} className="hidden" />
                        
                        {/* Scanning Overlay UI */}
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-72 h-72 border-2 border-indigo-500 rounded-3xl z-10 shadow-[0_0_100px_rgba(99,102,241,0.3)]">
                            <div className="absolute top-0 left-0 w-full h-1 bg-indigo-400 shadow-[0_0_20px_rgba(99,102,241,1)] animate-[scan_2s_infinite]"></div>
                            <div className="absolute inset-0 border-[20px] border-black/30 rounded-3xl"></div>
                            {/* Corner markers */}
                            <div className="absolute top-0 left-0 w-8 h-8 border-t-4 border-l-4 border-white rounded-tl-xl -mt-1 -ml-1"></div>
                            <div className="absolute top-0 right-0 w-8 h-8 border-t-4 border-r-4 border-white rounded-tr-xl -mt-1 -mr-1"></div>
                            <div className="absolute bottom-0 left-0 w-8 h-8 border-b-4 border-l-4 border-white rounded-bl-xl -mb-1 -ml-1"></div>
                            <div className="absolute bottom-0 right-0 w-8 h-8 border-b-4 border-r-4 border-white rounded-br-xl -mb-1 -mr-1"></div>
                        </div>
                        <div className="absolute bottom-40 w-full text-center z-20">
                             <p className="text-white/90 text-sm font-medium bg-black/40 backdrop-blur-md inline-block px-4 py-2 rounded-full border border-white/10">Align QR code within frame</p>
                        </div>
                      </>
                  ) : (
                      <div className="flex flex-col items-center justify-center text-center p-8 max-w-sm">
                          <div className="w-20 h-20 bg-amber-500/20 rounded-full flex items-center justify-center mb-6">
                              <AlertTriangle size={40} className="text-amber-500" />
                          </div>
                          <h3 className="text-xl font-bold mb-2">Scanner Unavailable</h3>
                          <p className="text-slate-300 mb-6">{scanError}</p>
                          <button onClick={() => setView('SCANNER')} className="px-6 py-3 bg-white/10 hover:bg-white/20 rounded-xl font-medium transition-colors border border-white/10">Try Again</button>
                      </div>
                  )}

                  {/* Manual Entry Fallback - Improved UI */}
                  <div className="absolute bottom-0 w-full px-6 pb-8 z-20 bg-gradient-to-t from-black via-black/80 to-transparent pt-12">
                      <div className="max-w-md mx-auto">
                          <p className="text-xs text-center text-slate-400 mb-3 uppercase tracking-wider font-semibold">Or enter manually</p>
                          <form onSubmit={handleManualSubmit} className="flex gap-3">
                            <input 
                                className="bg-white/10 backdrop-blur-md border border-white/20 rounded-xl px-5 py-4 flex-1 text-white placeholder:text-white/40 outline-none focus:border-indigo-500 focus:bg-white/15 transition-all font-mono" 
                                placeholder="Asset ID (e.g. AST-001)"
                                value={scanInput}
                                onChange={(e) => setScanInput(e.target.value)}
                            />
                            <button 
                                type="submit" 
                                disabled={!scanInput.trim()}
                                className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed px-6 rounded-xl transition-all font-bold shadow-lg shadow-indigo-900/50"
                            >
                                Go
                            </button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      );
  }

  // 3. Asset Detail (Verification)
  if (view === 'DETAIL' && selectedAsset) {
      return (
          <div className="min-h-screen bg-slate-50 dark:bg-slate-900 flex flex-col animate-in slide-in-from-bottom-10 duration-300">
               <div className="relative h-72 bg-slate-800 flex items-center justify-center">
                   {selectedAsset.imageUrl ? (
                       <img src={selectedAsset.imageUrl} className="w-full h-full object-cover opacity-80" alt="Asset" />
                   ) : (
                       <Package className="text-slate-500" size={64} />
                   )}
                   <div className="absolute inset-0 bg-gradient-to-t from-slate-900 to-transparent"></div>
                   <button onClick={() => setView('HOME')} className="absolute top-6 left-6 bg-white/10 backdrop-blur-md p-2 rounded-full text-white hover:bg-white/20 transition-colors border border-white/10"><ChevronLeft /></button>
                   <div className="absolute bottom-6 left-6 text-white max-w-[80%]">
                        <span className={`px-2 py-1 rounded-lg text-xs font-bold uppercase tracking-wider mb-2 inline-block ${selectedAsset.status === 'Active' ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30' : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'}`}>{selectedAsset.status}</span>
                        <h2 className="text-3xl font-bold leading-tight mb-1">{selectedAsset.name}</h2>
                        <p className="text-slate-300 font-mono text-sm">{selectedAsset.id}</p>
                   </div>
               </div>

               <div className="flex-1 p-6 -mt-6 bg-white dark:bg-slate-950 rounded-t-3xl relative z-10 flex flex-col shadow-[0_-10px_40px_rgba(0,0,0,0.2)]">
                   <div className="space-y-6 mb-8">
                       <div className="grid grid-cols-2 gap-4">
                           <InfoCard label="Serial" value={selectedAsset.serialNumber} />
                           <InfoCard label="Category" value={selectedAsset.category} />
                           <InfoCard label="Location" value={selectedAsset.location} />
                           <InfoCard label="Last Verified" value={selectedAsset.lastVerifiedDate ? new Date(selectedAsset.lastVerifiedDate).toLocaleDateString() : 'Never'} />
                       </div>
                   </div>

                   <div className="mt-auto space-y-3">
                       <button onClick={handleVerify} className="w-full bg-indigo-600 active:bg-indigo-700 text-white py-4 rounded-2xl font-bold text-lg shadow-lg shadow-indigo-200 dark:shadow-indigo-900/30 flex items-center justify-center gap-2 transform active:scale-95 transition-all">
                           <Check size={24} /> Mark as Verified
                       </button>
                       <button onClick={() => setView('COMPLAINT')} className="w-full bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-200 py-4 rounded-2xl font-bold text-lg flex items-center justify-center gap-2 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                           Report Issue
                       </button>
                   </div>
               </div>
          </div>
      );
  }

  // 4. Asset List
  if (view === 'ASSETS') {
      return (
          <div className="p-4 h-full flex flex-col bg-slate-50 dark:bg-slate-900">
              <div className="flex items-center gap-3 mb-6 pt-2">
                <button onClick={() => setView('HOME')} className="p-3 bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 text-slate-500 dark:text-slate-400"><ChevronLeft size={20} /></button>
                <div className="flex-1 relative">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/>
                    <input className="w-full pl-11 pr-4 py-3 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 outline-none focus:border-indigo-300 dark:focus:border-indigo-700 focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-900/20 transition-all font-medium text-slate-700 dark:text-slate-200 bg-white dark:bg-slate-800" placeholder="Search assets..." />
                </div>
              </div>
              <div className="flex-1 overflow-y-auto space-y-3 pb-20 pr-1 custom-scrollbar">
                  {assets.map(asset => (
                      <div key={asset.id} onClick={() => { setSelectedAsset(asset); setView('DETAIL'); }} className="bg-white dark:bg-slate-800 p-3 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 flex gap-4 items-center cursor-pointer active:scale-95 transition-transform">
                          <div className="w-16 h-16 rounded-xl overflow-hidden bg-slate-100 dark:bg-slate-700 shrink-0 flex items-center justify-center">
                              {asset.imageUrl ? (
                                  <img src={asset.imageUrl} className="w-full h-full object-cover" alt={asset.name} />
                              ) : (
                                  <Package className="text-slate-400 dark:text-slate-500" size={24} />
                              )}
                          </div>
                          <div className="flex-1 min-w-0">
                              <h3 className="font-bold text-slate-800 dark:text-white truncate">{asset.name}</h3>
                              <p className="text-xs text-slate-500 dark:text-slate-400 truncate mb-1">{asset.id} • {asset.location}</p>
                          </div>
                          <div className="pr-2">
                              <span className={`w-3 h-3 rounded-full block ${asset.status === 'Active' ? 'bg-emerald-500' : 'bg-amber-500'}`}></span>
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      );
  }

  // 5. Verified History
  if (view === 'VERIFIED') {
      const myLogs = logs.filter(l => l.verifiedBy === currentUser?.name);
      return (
          <div className="p-6 h-full flex flex-col bg-slate-50 dark:bg-slate-900">
              <div className="flex items-center gap-4 mb-8">
                <button onClick={() => setView('HOME')} className="p-2 bg-white dark:bg-slate-800 rounded-full shadow-sm text-slate-500 dark:text-slate-400"><ChevronLeft size={24} /></button>
                <h2 className="text-2xl font-bold text-slate-800 dark:text-white">History</h2>
              </div>
              
              <div className="space-y-4 overflow-y-auto pb-20">
                  {myLogs.length === 0 && (
                      <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                          <ClipboardCheck size={48} className="mb-4 opacity-20" />
                          <p>No verification history yet.</p>
                      </div>
                  )}
                  {myLogs.map(log => (
                      <div key={log.id} className="bg-white dark:bg-slate-800 p-5 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between">
                          <div>
                            <p className="font-bold text-slate-800 dark:text-white">{log.assetName}</p>
                            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{new Date(log.timestamp).toLocaleString()}</p>
                          </div>
                          <div className="bg-emerald-50 dark:bg-emerald-900/20 p-2 rounded-full text-emerald-600 dark:text-emerald-400">
                              <Check size={18} />
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      );
  }

  // 6. Complaint Form
  if (view === 'COMPLAINT') {
      return (
          <div className="p-6 min-h-screen bg-slate-50 dark:bg-slate-900 flex flex-col">
              <div className="flex justify-between items-center mb-8">
                 <button onClick={() => setView('HOME')} className="flex items-center gap-2 text-slate-500 dark:text-slate-400 font-medium"><ChevronLeft size={20}/> Cancel</button>
                 <h2 className="text-lg font-bold text-slate-800 dark:text-white">Report Issue</h2>
                 <div className="w-10"></div> 
              </div>
              
              <form onSubmit={handleComplaintSubmit} className="space-y-6 flex-1 flex flex-col">
                  {!selectedAsset ? (
                       <div className="bg-white dark:bg-slate-800 p-5 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700">
                          <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Asset ID</label>
                          <input 
                            className="w-full bg-slate-50 dark:bg-slate-900 p-4 rounded-xl font-medium outline-none focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-900 dark:text-white" 
                            placeholder="Enter ID (e.g. AST-001)"
                            required
                            onBlur={(e) => {
                                const found = assets.find(a => a.id === e.target.value);
                                if(found) setSelectedAsset(found);
                            }}
                          />
                       </div>
                  ) : (
                      <div className="bg-white dark:bg-slate-800 p-4 rounded-2xl border border-indigo-100 dark:border-slate-700 shadow-sm flex justify-between items-center">
                          <div className="flex items-center gap-3">
                              <div className="w-12 h-12 rounded-lg bg-slate-100 dark:bg-slate-700 overflow-hidden flex items-center justify-center">
                                  {selectedAsset.imageUrl ? (
                                      <img src={selectedAsset.imageUrl} className="w-full h-full object-cover"/>
                                  ) : (
                                      <Package className="text-slate-400 dark:text-slate-500" size={24} />
                                  )}
                              </div>
                              <div>
                                  <p className="font-bold text-slate-800 dark:text-white">{selectedAsset.name}</p>
                                  <p className="text-xs text-slate-500 dark:text-slate-400">{selectedAsset.id}</p>
                              </div>
                          </div>
                          <button type="button" onClick={() => setSelectedAsset(null)} className="p-2 bg-slate-50 dark:bg-slate-700 rounded-full text-slate-400"><X size={18} /></button>
                      </div>
                  )}

                  <div className="bg-white dark:bg-slate-800 p-5 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 flex-1">
                      <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Description</label>
                      <textarea 
                        className="w-full bg-slate-50 dark:bg-slate-900 p-4 rounded-xl h-full min-h-[150px] outline-none focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-900 resize-none font-medium text-slate-700 dark:text-white" 
                        placeholder="Please describe the issue in detail..."
                        value={complaintText}
                        onChange={e => setComplaintText(e.target.value)}
                        required
                      ></textarea>
                  </div>

                   <button type="button" className="w-full py-4 border-2 border-dashed border-slate-300 dark:border-slate-600 rounded-2xl text-slate-400 font-medium flex flex-col items-center justify-center gap-2 hover:bg-slate-50 dark:hover:bg-slate-800 hover:border-slate-400 transition-colors">
                       <Camera size={24} />
                       <span>Attach Photo Evidence</span>
                   </button>

                  <button type="submit" className="w-full bg-slate-900 dark:bg-indigo-600 text-white py-4 rounded-2xl font-bold text-lg shadow-lg shadow-slate-200 dark:shadow-indigo-900/30 mt-auto">Submit Report</button>
              </form>
          </div>
      );
  }

  return null;
};

const DashboardTile = ({ icon, title, subtitle, color, onClick, isPrimary, fullWidth }: any) => (
    <button 
        onClick={onClick}
        className={`p-6 rounded-3xl shadow-sm border dark:border-0 transition-all active:scale-95 text-left flex flex-col justify-between ${color} ${(isPrimary || fullWidth) ? 'col-span-2' : ''}`}
    >
        <div className={`p-3 rounded-2xl w-fit mb-4 ${isPrimary ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400' : 'bg-slate-50 dark:bg-slate-700'}`}>
            {icon}
        </div>
        <div>
            <h3 className="font-bold text-lg">{title}</h3>
            <p className="text-xs font-medium opacity-70">{subtitle}</p>
        </div>
    </button>
);

const InfoCard = ({ label, value }: { label: string, value: string }) => (
    <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-2xl border border-slate-100 dark:border-slate-700">
        <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">{label}</p>
        <p className="font-semibold text-slate-800 dark:text-slate-200 truncate" title={value}>{value}</p>
    </div>
);
